=== csharptest/NClassify/src/NClassify.Generator/NClassifyConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="NClassify" nillable="true" type="NClassifyConfig" />
  <xs:complexType name="NClassifyConfig">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="settings" type="NClassifySettings" />
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="type" type="ComplexType" />
        <xs:element minOccurs="0" maxOccurs="1" name="service" type="ServiceInfo" />
        <xs:element minOccurs="0" maxOccurs="1" name="enum" type="EnumType" />
        <xs:element minOccurs="0" maxOccurs="1" name="import" type="ImportFile" />
        <xs:element minOccurs="0" maxOccurs="1" name="value" type="SimpleType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NClassifySettings">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="namespace" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ComplexType">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseType">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="fields" type="ArrayOfChoice2" />
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="enum" type="EnumType" />
            <xs:element minOccurs="0" maxOccurs="1" name="type" type="ComplexType" />
            <xs:element minOccurs="0" maxOccurs="1" name="value" type="SimpleType" />
          </xs:choice>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BaseType" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="RootItem">
        <xs:attribute name="name" type="xs:NCName" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="RootItem" abstract="true" />
  <xs:complexType name="ImportFile">
    <xs:complexContent mixed="false">
      <xs:extension base="RootItem">
        <xs:attribute name="file" type="xs:anyURI" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ServiceInfo">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseType">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="method" type="ServiceMethod" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ServiceMethod">
    <xs:attribute name="name" type="xs:NCName" />
    <xs:attribute name="returns" type="xs:NCName" />
    <xs:attribute name="argument" type="xs:NCName" />
  </xs:complexType>
  <xs:complexType name="SimpleType">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseType">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="validation" type="ArrayOfChoice3" />
        </xs:sequence>
        <xs:attribute name="base" type="FieldType" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfChoice3">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element minOccurs="1" maxOccurs="1" name="predefined" nillable="true" type="PredefinedValue" />
      <xs:element minOccurs="1" maxOccurs="1" name="length" nillable="true" type="LengthConstraint" />
      <xs:element minOccurs="1" maxOccurs="1" name="range" nillable="true" type="RangeConstraint" />
      <xs:element minOccurs="1" maxOccurs="1" name="match" nillable="true" type="MatchConstraint" />
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="PredefinedValue">
    <xs:complexContent mixed="false">
      <xs:extension base="ValidationRule">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="value" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValidationRule" abstract="true" />
  <xs:complexType name="MatchConstraint">
    <xs:complexContent mixed="false">
      <xs:extension base="ValidationRule">
        <xs:attribute default=".*" name="pattern" type="xs:string" />
        <xs:attribute default="false" name="ignoreCase" type="xs:boolean" />
        <xs:attribute default="false" name="multiline" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="RangeConstraint">
    <xs:complexContent mixed="false">
      <xs:extension base="ValidationRule">
        <xs:attribute name="min" type="xs:string" />
        <xs:attribute name="max" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="LengthConstraint">
    <xs:complexContent mixed="false">
      <xs:extension base="ValidationRule">
        <xs:attribute default="0" name="min" type="xs:unsignedInt" />
        <xs:attribute default="4294967295" name="max" type="xs:unsignedInt" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="FieldType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="bool" />
      <xs:enumeration value="bytes" />
      <xs:enumeration value="int8" />
      <xs:enumeration value="uint8" />
      <xs:enumeration value="int16" />
      <xs:enumeration value="uint16" />
      <xs:enumeration value="int32" />
      <xs:enumeration value="uint32" />
      <xs:enumeration value="int64" />
      <xs:enumeration value="uint64" />
      <xs:enumeration value="float" />
      <xs:enumeration value="double" />
      <xs:enumeration value="guid" />
      <xs:enumeration value="dateTime" />
      <xs:enumeration value="timeSpan" />
      <xs:enumeration value="string" />
      <xs:enumeration value="uri" />
      <xs:enumeration value="email" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="EnumType">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseType">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="value" type="Item" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Item">
    <xs:attribute name="name" type="xs:NCName" />
    <xs:attribute name="ordinal" type="xs:unsignedInt" use="required" />
  </xs:complexType>
  <xs:complexType name="ArrayOfChoice2">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element minOccurs="1" maxOccurs="1" name="primitive" nillable="true" type="Primitive" />
      <xs:element minOccurs="1" maxOccurs="1" name="enum" nillable="true" type="EnumTypeRef" />
      <xs:element minOccurs="1" maxOccurs="1" name="complex" nillable="true" type="ComplexTypeRef" />
      <xs:element minOccurs="1" maxOccurs="1" name="simple" nillable="true" type="SimpleTypeRef" />
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="Primitive">
    <xs:complexContent mixed="false">
      <xs:extension base="FieldInfo">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="validation" type="ArrayOfChoice1" />
        </xs:sequence>
        <xs:attribute name="type" type="FieldType" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="FieldInfo" abstract="true">
    <xs:attribute name="default" type="xs:string" />
    <xs:attribute name="name" type="xs:NCName" />
    <xs:attribute name="property" type="xs:NCName" />
    <xs:attribute name="ordinal" type="xs:unsignedInt" use="required" />
    <xs:attribute default="public" name="access" type="FieldAccess" />
    <xs:attribute default="false" name="array" type="xs:boolean" />
    <xs:attribute default="read-write" name="direction" type="FieldDirection" />
    <xs:attribute default="optional" name="use" type="FieldUse" />
  </xs:complexType>
  <xs:simpleType name="FieldAccess">
    <xs:restriction base="xs:string">
      <xs:enumeration value="public" />
      <xs:enumeration value="private" />
      <xs:enumeration value="protected" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="FieldDirection">
    <xs:restriction base="xs:string">
      <xs:enumeration value="read-write" />
      <xs:enumeration value="read-only" />
      <xs:enumeration value="write-only" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="FieldUse">
    <xs:restriction base="xs:string">
      <xs:enumeration value="optional" />
      <xs:enumeration value="required" />
      <xs:enumeration value="obsolete" />
      <xs:enumeration value="prohibited" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="EnumTypeRef">
    <xs:complexContent mixed="false">
      <xs:extension base="FieldInfo">
        <xs:attribute name="type" type="xs:NCName" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimpleTypeRef">
    <xs:complexContent mixed="false">
      <xs:extension base="FieldInfo">
        <xs:attribute name="type" type="xs:NCName" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ComplexTypeRef">
    <xs:complexContent mixed="false">
      <xs:extension base="FieldInfo">
        <xs:attribute name="type" type="xs:NCName" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfChoice1">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element minOccurs="1" maxOccurs="1" name="predefined" nillable="true" type="PredefinedValue" />
      <xs:element minOccurs="1" maxOccurs="1" name="length" nillable="true" type="LengthConstraint" />
      <xs:element minOccurs="1" maxOccurs="1" name="range" nillable="true" type="RangeConstraint" />
      <xs:element minOccurs="1" maxOccurs="1" name="match" nillable="true" type="MatchConstraint" />
    </xs:choice>
  </xs:complexType>
</xs:schema>

=== csharptest/NClassify/src/NClassify.Generator/Example.xml
<?xml version="1.0" encoding="utf-8" ?>
<NClassify xsi:noNamespaceSchemaLocation="NClassifyConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <settings>
    <namespace>NClassify.Example</namespace>
  </settings>

  <value name="SimpleInt32" base="int32">
    <validation>
      <range min="1" />
    </validation>
  </value>

  <enum name="SampleEnum">
    <value name="one" ordinal="1"/>
    <value name="two" ordinal="2"/>
    <value name="three" ordinal="3"/>
  </enum>

  <value name="SimpleBytes" base="bytes">
    <validation>
      <length min="1" max="255" />
    </validation>
  </value>

  <value name="SimpleText" base="string">
    <validation>
      <predefined>
        <value>abc</value>
        <value>def</value>
        <value>ghi</value>
        <value>jkl</value>
        <value>mno</value>
        <value>pqr</value>
        <value>stu</value>
        <value>vwx</value>
        <value>yz</value>
      </predefined>
    </validation>
  </value>
  
  <value name="simple_uri" base="string">
    <validation>
      <length min="8" max="2048" />
      <match ignoreCase="true" pattern="^https?\://.+" />
      <code language="C#" test="IsValidUri(value)">
        <!--signature is: bool IsValidUri(string value) {-->
        <method>
          global::System.Uri tmp;
          return global::System.Uri.TryCreate(value, global::System.UriKind.Absolute, out tmp);
        </method>
      </code>
    </validation>
  </value>

  <type name="SampleMsg">
    <fields>
      <simple ordinal="1" name="Id" type="SimpleInt32" default="0" />
      <simple ordinal="2" name="uri" type="simple_uri" default="" />
      <simple ordinal="3" name="alpha_group" type="SimpleText" use="required" default="abc" />
      <enum ordinal="4" name="enum" type="SampleEnum" default="1" />
      <simple ordinal="5" name="bytes" type="SimpleBytes" />

      <primitive ordinal="10" name="verified" type="bool" />
      <primitive ordinal="11" name="errors" type="string" array="true" direction="read-only" property="readErrors" access="protected">
        <validation>
          <length max="0"/>
        </validation>
      </primitive>
      
      <complex ordinal="20" name="children" type="SampleMsg" array="true" />
    </fields>
  </type>

  <type name="SingleFields">
    <fields>
      <!-- The following are all valid types types of non-array fields -->
      <primitive ordinal="11" name="bool" type="bool" default="1" />
      <primitive ordinal="12" name="bytes" type="bytes" default="asdf" />
      <primitive ordinal="13" name="int8" type="int8" default="1" />
      <primitive ordinal="14" name="uint8" type="uint8" default="1" />
      <primitive ordinal="15" name="int16" type="int16" default="1" />
      <primitive ordinal="16" name="uint16" type="uint16" default="1" />
      <primitive ordinal="17" name="int32" type="int32" default="1" />
      <primitive ordinal="18" name="uint32" type="uint32" default="1" />
      <primitive ordinal="19" name="int64" type="int64" default="1" />
      <primitive ordinal="20" name="uint64" type="uint64" default="1" />
      <primitive ordinal="21" name="float" type="float" default="1" />
      <primitive ordinal="22" name="double" type="double" default="1" />
      <primitive ordinal="23" name="guid" type="guid" default="new()" />
      <primitive ordinal="24" name="dateTime" type="dateTime" default="now()" />
      <primitive ordinal="25" name="timeSpan" type="timeSpan" default="1:00" />
      <primitive ordinal="26" name="string" type="string" default="1" />
      <enum      ordinal="27" name="enum" type="SampleEnum" default="2" />
      <simple    ordinal="28" name="simple_int32" type="SimpleInt32" default="2" />
      <simple    ordinal="29" name="simple_uri" type="simple_uri" default="http://example.uri" />
      <simple    ordinal="30" name="simple_text" type="SimpleText" use="required" default="def" />
      <simple    ordinal="31" name="simple_bytes" type="SimpleBytes" default="AsdF12==" />
      <complex   ordinal="32" name="sample_msg" type="SampleMsg" />
    </fields>
  </type>

  <type name="ArrayFields">
    <fields>
      <!-- The following are all valid types types of array fields -->
      <primitive ordinal="11" name="bool" type="bool" array="true" />
      <primitive ordinal="12" name="bytes" type="bytes" array="true" />
      <primitive ordinal="13" name="int8" type="int8" array="true" />
      <primitive ordinal="14" name="uint8" type="uint8" array="true" />
      <primitive ordinal="15" name="int16" type="int16" array="true" />
      <primitive ordinal="16" name="uint16" type="uint16" array="true" />
      <primitive ordinal="17" name="int32" type="int32" array="true" />
      <primitive ordinal="18" name="uint32" type="uint32" array="true" />
      <primitive ordinal="19" name="int64" type="int64" array="true" />
      <primitive ordinal="20" name="uint64" type="uint64" array="true" />
      <primitive ordinal="21" name="float" type="float" array="true" />
      <primitive ordinal="22" name="double" type="double" array="true" />
      <primitive ordinal="23" name="guid" type="guid" array="true" />
      <primitive ordinal="24" name="dateTime" type="dateTime" array="true" />
      <primitive ordinal="25" name="timeSpan" type="timeSpan" array="true" />
      <primitive ordinal="26" name="string" type="string" array="true" />
      <enum      ordinal="27" name="enum" type="SampleEnum" array="true" />
      <simple    ordinal="28" name="simple_int32" type="SimpleInt32" array="true" />
      <simple    ordinal="29" name="simple_uri" type="simple_uri" array="true" />
      <simple    ordinal="30" name="simple_text" type="SimpleText" use="required" array="true" />
      <simple    ordinal="31" name="simple_bytes" type="SimpleBytes" array="true" />
      <complex   ordinal="32" name="sample_msg" type="SampleMsg" array="true" />
    </fields>
  </type>

  <service name="CallbackService">
    <method name="Get" returns="SampleMsg" />
    <method name="Put" argument="SampleMsg" returns="SampleMsg" />
    <method name="Delete" argument="SampleMsg" />
  </service>

</NClassify>

=== csharptest/NClassify/src/NClassify.Example/Example.xml
<?xml version="1.0" encoding="utf-8" ?>
<NClassify xsi:noNamespaceSchemaLocation="..\NClassify.Generator\NClassifyConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <settings>
    <namespace>NClassify.Example</namespace>
    <xml-defaults form="element" namespace-uri="http://nclassify.com/schema/v1/example">
      <formatting type="dateTime" format="yyyy-MM-dd hh:mm:ss"/>
    </xml-defaults>
  </settings>

  <value name="SimpleInt32" base="int32">
    <validation>
      <range min="1" />
    </validation>
  </value>

  <enum name="SampleEnum">
    <value name="one" ordinal="1"/>
    <value name="two" ordinal="2"/>
    <value name="three" ordinal="3"/>
  </enum>

  <value name="SimpleBytes" base="bytes">
    <validation>
      <length min="1" max="255" />
    </validation>
  </value>

  <value name="SimpleText" base="string">
    <validation>
      <predefined>
        <value>abc</value>
        <value>def</value>
        <value>ghi</value>
        <value>jkl</value>
        <value>mno</value>
        <value>pqr</value>
        <value>stu</value>
        <value>vwx</value>
        <value>yz</value>
      </predefined>
    </validation>
  </value>
  
  <value name="simple_uri" base="string">
    <validation>
      <length min="8" max="2048" />
      <match ignoreCase="true" pattern="^https?\://.+" />
      <code language="C#" test="IsValidUri(value)">
        <!--signature is: bool IsValidUri(string value) {-->
        <method>
          global::System.Uri tmp;
          return global::System.Uri.TryCreate(value, global::System.UriKind.Absolute, out tmp);
        </method>
      </code>
    </validation>
  </value>
  <message name="CircleA">
    <fields>
      <message ordinal="1" name="B" type="CircleB"/>
    </fields>
  </message>
  <message name="CircleB">
    <fields>
      <message ordinal="1" name="A" type="CircleA"/>
    </fields>
  </message>
  <message name="CircleC" inherits="CircleA">
    <fields>
    </fields>
  </message>
  <message name="SampleMsg">
    <fields>
      <value ordinal="1" name="Id" type="SimpleInt32" default="0" />
      <value ordinal="2" name="uri" type="simple_uri" default="" />
      <value ordinal="3" name="alpha_group" type="SimpleText" use="required" default="abc" />
      <enum  ordinal="4" name="enum" type="SampleEnum" default="1" />
      <value ordinal="5" name="bytes" type="SimpleBytes" />

      <primitive ordinal="10" name="verified" type="bool" />
      <primitive ordinal="11" name="errors" type="string" array="true" direction="read-only" property="ReadErrors" access="protected">
        <validation>
          <length max="0"/>
        </validation>
      </primitive>
      
      <message ordinal="20" name="children" type="SampleMsg" array="true" />

      <primitive ordinal="31" name="dateModified" type="dateTime" array="true">
        <xml-options array-item-name="item" name="mod-date" form="element" format="yy-m-d" />
      </primitive>

      <!-- Intentional name collisions -->
      <primitive ordinal="100" name="IsValid" type="bool" />
      <primitive ordinal="102" name="AssertValid" type="bool" />
      <primitive ordinal="103" name="GetBrokenRules" type="bool" />
      <primitive ordinal="104" name="Clear" type="bool" />
      <primitive ordinal="105" name="Initialize" type="bool" />
      <primitive ordinal="106" name="MergeFrom" type="bool" />
      <primitive ordinal="107" name="MergeTo" type="bool" />
      <primitive ordinal="108" name="ReadXml" type="bool" />
      <primitive ordinal="109" name="WriteXml" type="bool" />
      <primitive ordinal="110" name="TypeFields" type="bool" />
    </fields>
  </message>

  <message name="SingleFields">
    <fields>
      <!-- The following are all valid types types of non-array fields -->
      <primitive ordinal="11" name="bool" type="bool" default="1" />
      <primitive ordinal="12" name="bytes" type="bytes" default="asdf" />
      <primitive ordinal="13" name="int8" type="int8" default="1" />
      <primitive ordinal="14" name="uint8" type="uint8" default="1" />
      <primitive ordinal="15" name="int16" type="int16" default="1" />
      <primitive ordinal="16" name="uint16" type="uint16" default="1" />
      <primitive ordinal="17" name="int32" type="int32" default="1" />
      <primitive ordinal="18" name="uint32" type="uint32" default="1" />
      <primitive ordinal="19" name="int64" type="int64" default="1" />
      <primitive ordinal="20" name="uint64" type="uint64" default="1" />
      <primitive ordinal="21" name="float" type="float" default="1" />
      <primitive ordinal="22" name="double" type="double" default="1" />
      <primitive ordinal="23" name="guid" type="guid" default="new()" />
      <primitive ordinal="24" name="dateTime" type="dateTime" default="now()" />
      <primitive ordinal="25" name="timeSpan" type="timeSpan" default="1:00" />
      <primitive ordinal="26" name="string" type="string" default="1" />
      <enum      ordinal="27" name="enum" type="SampleEnum" default="2" />
      <value     ordinal="28" name="simple_int32" type="SimpleInt32" default="2" />
      <value     ordinal="29" name="simple_uri" type="simple_uri" default="http://example.uri" />
      <value     ordinal="30" name="simple_text" type="SimpleText" use="required" default="def" />
      <value     ordinal="31" name="simple_bytes" type="SimpleBytes" default="AsdF12==" />
      <message   ordinal="32" name="sample_msg" type="SampleMsg" />
      <message   ordinal="33" name="i_sample_msg" type="ISampleMsg" />
    </fields>
  </message>

  <message name="ArrayFields">
    <fields>
      <!-- The following are all valid types types of array fields -->
      <primitive ordinal="11" name="bool" type="bool" array="true" />
      <primitive ordinal="12" name="bytes" type="bytes" array="true" />
      <primitive ordinal="13" name="int8" type="int8" array="true" />
      <primitive ordinal="14" name="uint8" type="uint8" array="true" />
      <primitive ordinal="15" name="int16" type="int16" array="true" />
      <primitive ordinal="16" name="uint16" type="uint16" array="true" />
      <primitive ordinal="17" name="int32" type="int32" array="true" />
      <primitive ordinal="18" name="uint32" type="uint32" array="true" />
      <primitive ordinal="19" name="int64" type="int64" array="true" />
      <primitive ordinal="20" name="uint64" type="uint64" array="true" />
      <primitive ordinal="21" name="float" type="float" array="true" />
      <primitive ordinal="22" name="double" type="double" array="true" />
      <primitive ordinal="23" name="guid" type="guid" array="true" />
      <primitive ordinal="24" name="dateTime" type="dateTime" array="true" />
      <primitive ordinal="25" name="timeSpan" type="timeSpan" array="true" />
      <primitive ordinal="26" name="string" type="string" array="true" />
      <enum      ordinal="27" name="enum" type="SampleEnum" array="true" />
      <value     ordinal="28" name="simple_int32" type="SimpleInt32" array="true" />
      <value     ordinal="29" name="simple_uri" type="simple_uri" array="true" />
      <value     ordinal="30" name="simple_text" type="SimpleText" use="required" array="true" />
      <value     ordinal="31" name="simple_bytes" type="SimpleBytes" array="true" />
      <message   ordinal="32" name="sample_msg" type="SampleMsg" array="true" />
      <message   ordinal="33" name="i_sample_msg" type="ISampleMsg" array="true" />
    </fields>
  </message>

  <service name="ExampleService">
    <method name="Ping" />
    <method name="Get" returns="ISampleMsg" />
    <method name="Put" argument="SampleMsg" returns="SampleMsg" />
    <method name="Delete" argument="ISampleMsg" />
  </service>

</NClassify>
